# Generated by Django 5.2.5 on 2025-09-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Science Fiction'), ('thriller', 'Thriller'), ('documentary', 'Documentary'), ('animation', 'Animation'), ('other', 'Other')], default='other', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail-Bild (320x180px empfohlen)', null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Alternative: Thumbnail-URL', null=True)),
                ('poster', models.ImageField(blank=True, help_text='Poster-Bild (1280x720px empfohlen)', null=True, upload_to='posters/')),
                ('background', models.ImageField(blank=True, help_text='Hintergrund-Bild (1920x1080px empfohlen)', null=True, upload_to='backgrounds/')),
                ('video_file', models.FileField(blank=True, help_text='Video-Datei (MP4 empfohlen)', null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='Alternative: Video-URL', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
