# Generated by Django 5.2.5 on 2025-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='background',
            field=models.ImageField(blank=True, help_text='Background image (1920x1080px recommended)', null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster image (1280x720px recommended)', null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image (320x180px recommended)', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative: Thumbnail URL', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video file (MP4 recommended)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternative: Video URL', null=True),
        ),
    ]
