# Generated by Django 5.2.5 on 2025-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_alter_customuser_managers_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='background',
            field=models.ImageField(blank=True, help_text='Hintergrund-Bild (1920x1080px empfohlen)', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster-Bild (1280x720px empfohlen)', null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail-Bild (320x180px empfohlen)', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternative: Video-URL', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative: Thumbnail-URL', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video-Datei (MP4 empfohlen)', null=True, upload_to='videos/'),
        ),
    ]
